### ISSUE TITLE
Support mutable devices

### ISSUE THREAD

**Issue by robinkrahl** [d-e-s-o/nitrokey-test#3]
As discussed on the nitrokey-rs-dev mailing list, it would make sense to take a mutable Device reference in some functions.  So some tests have to take a mutable Device as input.  Could you add support for that to nitrokey-test?

**Comment by d-e-s-o** [comment]
Will do.

**Comment by d-e-s-o** [comment]
(btw., you can always do:
```rust
let mut device = device;
```
so this detail shouldn't block you)

**Comment by robinkrahl** [comment]
> (btw., you can always do:
> ```rust
> let mut device = device;
> ```
> so this detail shouldn't block you)

Yeah, I’ll use that as a workaround, thanks!

**Comment by d-e-s-o** [comment]
You can check out the [`devel` branch](https://github.com/d-e-s-o/nitrokey-test/tree/devel) which should have everything required. Haven't tested it with `nitrokey` yet, though.

**Comment by d-e-s-o** [comment]
I forgot about this issue. I don't think mutable device objects are a problem anymore (though I don't recall which commit precisely enabled that). I just tried it out with
```patch
--- tests/mod.rs
+++ tests/mod.rs
@@ -34,9 +34,10 @@ fn no_dev() {
 }

 #[nitrokey_test::test]
-fn pro(device: Pro) {
+fn pro(mut device: Pro) {
   assert_eq!(device.get_model(), Model::Pro);

+  let _ = device.lock();
   let manager = device.into_manager();
   assert!(manager.connect_pro().is_ok())
 }
```
And it compiled fine. So I am going to close this issue.
