### ISSUE TITLE
Update proc-macro2 to 1.0

### ISSUE THREAD

**Issue by kpcyrd** [d-e-s-o/nitrokey-test#5]
Thanks!

**Comment by d-e-s-o** [comment]
Absolutely, it's high up on my list of things to do next.

**Comment by d-e-s-o** [comment]
Pushed to `devel`. Do you need a new release @kpcyrd ?

**Comment by d-e-s-o** [comment]
Closing as per the above. Let me know in case you need a release quickly.

**Comment by kpcyrd** [comment]
Thanks for the quick reply and fix! I don't need a new release urgently, feel free to do one eventually when convenient, but the offer is much appreciated. :)

**Comment by kpcyrd** [comment]
We have most proc-macro2 crates updated by now, a new release for nitrokey-test soonish would be appreciated :)

**Comment by d-e-s-o** [comment]
Done.

**Comment by d-e-s-o** [comment]
Do you mind sharing what kind of project you are using the crate in, @kpcyrd?

**Comment by kpcyrd** [comment]
I'm trying to update the [debian package](https://tracker.debian.org/pkg/rust-nitrokey-test). It was uploaded by the maintainer of nitrocli (probably as a dependency for something), but I'm not sure what it's actually used for since `aptitude search '~Dlibrust-nitrokey-test'` doesn't return any results. (cc: @robinkrahl)

**Comment by robinkrahl** [comment]
I packaged nitrokey-test in preparation for the next nitrokey-rs and
nitrocli releases (which will depend on nitrokey-test).  But I did not
yet get to actually releasing the new nitrokey-rs version.
